seed_everything: 0
model:
  class_path: pytorch_gleam.modeling.models.ContrastiveFrameLanguageModel
  init_args:
    learning_rate: 1e-5
    lr_warm_up: 0.01
    pre_model_name: digitalepidemiologylab/covid-twitter-bert-v2
    loss:
      class_path: pytorch_gleam.modeling.losses.MarginContrastiveLoss
      init_args:
        margin: 2.0

trainer:
  accelerator: gpu
  devices: 1
  default_root_dir: /users/max/data/models/ct/ct-v21
  max_epochs: 100
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 1
  deterministic: true
  num_sanity_val_steps: 1
  enable_checkpointing: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_gleam.callbacks.TPURichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
data:
  class_path: pytorch_gleam.data.datasets.ContrastiveFrameDataModule
  init_args:
    batch_size: 8
    max_seq_len: 96
    label_name: labels
    tokenizer_name: digitalepidemiologylab/covid-twitter-bert-v2
    num_workers: 8
    frame_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames.json
    train_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames-train.jsonl
    val_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames-dev.jsonl
    test_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames-test.jsonl
