seed_everything: 0
model:
  class_path: pytorch_gleam.modeling.models.MultiClassFrameImageBridgeTowerModel
  init_args:
    learning_rate: 3e-5
    lr_warm_up: 0.0
    pre_model_name: BridgeTower/bridgetower-base
    label_map:
      No_Stance: 0
      Accept: 1
      Reject: 2
    threshold:
      class_path: pytorch_gleam.modeling.thresholds.MultiClassThresholdModule
    metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: macro
        num_classes: 3

trainer:
  max_epochs: 1
  accumulate_grad_batches: 16
  check_val_every_n_epoch: 1
  val_check_interval: 1000
  deterministic: true
  num_sanity_val_steps: 1
  accelerator: gpu
  devices: 1
  default_root_dir: /shared/aifiles/disk1/covid19/models/mm-stance/pre-bt-v33
  enable_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      name: pre-bt-v33
      project: "mm-stance"
      save_dir: /shared/aifiles/disk1/covid19/logs/mm-stance
      dir: /shared/aifiles/disk1/covid19/logs/mm-stance
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
    - class_path: pytorch_gleam.callbacks.WandbConfig
data:
  class_path: pytorch_gleam.data.datasets.MultiClassFrameImageRelationDataModule
  init_args:
    text_stance_path: /shared/hltdir4/disk1/team/data/models/mm-stance/pre-ds-v2/text-stance-preds.json
    # Sources in the format "Text Stance|Joint Stance|Image Stance"
    # where Image stance is inferred
    sources:
      - No_Stance|Accept|Accept
      - No_Stance|Reject|Reject
    # Relations in the format "Text Stance|Joint Stance|Image Stance"
    # where image & image stance is borrowed from source
    relations:
      - Accept|Accept|Accept
      - Reject|Reject|Reject
    keep_original: true
    batch_size: 4
    max_seq_len: 512
    label_name: labels
    label_map:
      No_Stance: 0
      Accept: 1
      Reject: 2
    processor_name: BridgeTower/bridgetower-base
    num_workers: 8
    skip_unknown_labels: true
    frame_path: /shared/aifiles/disk1/media/twitter/v10/data/frames.json
    train_path: /shared/aifiles/disk1/media/twitter/v10/data/train.jsonl
    val_path: /shared/aifiles/disk1/media/twitter/v10/data/dev.jsonl
    test_path: /shared/aifiles/disk1/media/twitter/v10/data/test.jsonl
