seed_everything: 0
model:
  class_path: pytorch_gleam.modeling.models.ContrastiveChannelLanguageModel
  init_args:
    learning_rate: 1e-4
    pre_model_name: t5-base
    num_val_seeds: 1
    contrastive:
      class_path: pytorch_gleam.modeling.losses.MarginContrastiveLoss
      init_args:
        margin: 4.0
    infer:
      class_path: pytorch_gleam.inference.MultiHopConsistencyScoring
      init_args:
        num_steps: 32
        num_classes: 3
    threshold:
      class_path: pytorch_gleam.modeling.thresholds.MultiClassMultiLabelThresholdModule
    metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: macro
        num_classes: 3
    m_metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: micro
        num_classes: 3

trainer:
  max_epochs: 36
  accumulate_grad_batches: 8
  check_val_every_n_epoch: 4
  deterministic: true
  num_sanity_val_steps: 0
  accelerator: gpu
  devices: 1
  default_root_dir: /shared/hltdir4/disk1/team/data/models/cvl-cncac/cncac-v1
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
    # - class_path: pytorch_gleam.callbacks.JsonlWriter
data:
  class_path: pytorch_gleam.data.datasets.ContrastiveChannelMisinfoStanceDataModule
  init_args:
    batch_size: 4
    pos_samples: 1
    neg_samples: 1
    max_seq_len: 512
    num_workers: 8
    tokenizer_name: t5-base
    misinfo_path: /users/max/data/corpora/vaccine-lies/covid19/taxonomy/misinfo.json
    train_path: /users/max/data/corpora/vaccine-lies/covid19/annotations-and-data/train.jsonl
    val_path: /users/max/data/corpora/vaccine-lies/covid19/annotations-and-data/dev.jsonl
    # test_path: /users/max/data/corpora/vaccine-lies/covid19/annotations-and-data/test.jsonl
