seed_everything: 0
model:
  class_path: pytorch_gleam.modeling.models.MultiClassFrameLanguageModel
  init_args:
    learning_rate: 1e-4
    pre_model_name: digitalepidemiologylab/covid-twitter-bert-v2
    label_map:
      No Stance: 0
      Accept: 1
      Reject: 2
    threshold:
      class_path: pytorch_gleam.modeling.thresholds.MultiClassThresholdModule
    metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: macro
        num_classes: 3

trainer:
  max_epochs: 10
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 1
  deterministic: true
  num_sanity_val_steps: 1
  accelerator: gpu
  devices: 1
  default_root_dir: /shared/hltdir4/disk1/team/data/models/mm-stance/pre-ds-v1
  enable_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: "mm-stance"
      save_dir: /shared/hltdir4/disk1/team/data/models/clearml
      dir: /shared/hltdir4/disk1/team/data/models/clearml
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
    - class_path: pytorch_gleam.callbacks.WandbConfig
    - class_path: pytorch_gleam.callbacks.JsonlWriter
data:
  class_path: pytorch_gleam.data.datasets.MultiClassFrameDataModule
  init_args:
    batch_size: 8
    max_seq_len: 128
    label_name: labels
    label_map:
      No Stance: 0
      Accept: 1
      Reject: 2
    tokenizer_name: digitalepidemiologylab/covid-twitter-bert-v2
    num_workers: 8
    skip_unknown_labels: true
    frame_path: /shared/aifiles/disk1/media/twitter/v10/data/frames.json
    predict_path: /shared/aifiles/disk1/media/twitter/v10/data/train.jsonl
