data:
  class_path: pytorch_gleam.data.datasets.MultiClassFrameDataModule
  init_args:
    batch_size: 20
    frame_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames.json
    label_map:
      Accept: 1
      Not Relevant: 0
      Reject: 2
    label_name: labels
    max_seq_len: 96
    num_workers: 8
    tokenizer_name: digitalepidemiologylab/covid-twitter-bert-v2
    train_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames-train.jsonl
    val_path: /shared/hltdir4/disk1/team/data/corpora/co-vax-frames/covid19/co-vax-frames-dev.jsonl
model:
  class_path: pytorch_gleam.modeling.models.MultiClassFrameLanguageModel
  init_args:
    label_map:
      Accept: 1
      Not Relevant: 0
      Reject: 2
    learning_rate: 1.9e-05
    lr_warm_up: 0.15
    metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: macro
        num_classes: 3
    pre_model_name: digitalepidemiologylab/covid-twitter-bert-v2
    threshold:
      class_path: pytorch_gleam.modeling.thresholds.MultiClassThresholdModule
    weight_decay: 0.008
seed_everything: 0
trainer:
  accelerator: gpu
  accumulate_grad_batches: 1
  callbacks:
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
  - class_path: pytorch_lightning.callbacks.RichProgressBar
    init_args:
      leave: true
  - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
  - class_path: pytorch_gleam.callbacks.WandbConfig
  check_val_every_n_epoch: 1
  default_root_dir: /shared/aifiles/disk1/covid19/models/gpt-opt/bert-v8
  deterministic: true
  devices: 1
  enable_checkpointing: false
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      dir: /shared/aifiles/disk1/covid19/logs/gpt-opt
      project: gpt-opt
      save_dir: /shared/aifiles/disk1/covid19/logs/gpt-opt
  max_epochs: 4
  num_sanity_val_steps: 1