seed_everything: 0
model:
  class_path: pytorch_gleam.modeling.models.MultiClassFrameLanguageModel
  init_args:
    learning_rate: 5e-1
    pre_model_name: digitalepidemiologylab/covid-twitter-bert-v2
    label_map:
      No Stance: 0
      Accept: 1
      Reject: 2
    threshold:
      class_path: pytorch_gleam.modeling.thresholds.MultiClassThresholdModule
    metric:
      class_path: pytorch_gleam.modeling.metrics.F1PRMultiClassMetric
      init_args:
        mode: macro
        num_classes: 3

trainer:
  accelerator: gpu
  devices: 1
  default_root_dir: /users/max/data/models/vax-bert-ft/vax-bert-baseline-stance-v4
  max_epochs: 10
  accumulate_grad_batches: 4
  check_val_every_n_epoch: 1
  deterministic: true
  num_sanity_val_steps: 1
  enable_checkpointing: false
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_gleam.callbacks.TPURichProgressBar
      init_args:
        leave: true
    - class_path: pytorch_gleam.callbacks.FitCheckpointCallback
data:
  class_path: pytorch_gleam.data.datasets.MultiClassFrameDataModule
  init_args:
    batch_size: 8
    max_seq_len: 128
    label_name: misinfo
    label_map:
      No Stance: 0
      Accept: 1
      Reject: 2
    tokenizer_name: digitalepidemiologylab/covid-twitter-bert-v2
    num_workers: 8
    frame_path:
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/covid-19/misinfo.json
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/hpv/misinfo.json
    train_path:
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/covid-19/stance-train.jsonl
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/hpv/stance-train.jsonl
    val_path:
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/covid-19/stance-dev.jsonl
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/hpv/stance-dev.jsonl
    test_path:
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/covid-19/stance-test.jsonl
      - /shared/hltdir4/disk1/team/data/corpora/vax-lies/hpv/stance-test.jsonl
